### ISSUE TITLE
get the file name list in a S3 folder?

### ISSUE THREAD

**Issue by jingpengwu** [JuliaParallel/AWS.jl#65]
is there any function available to get the file name list of a folder?
I found the function to list the buckets, but not in the folders.

**Comment by jingpengwu** [comment]
just find an alternative way:
`resp = readall(`aws s3 ls s3://znn`)`
but this is not a perfect julia way...

**Comment by mdpradeep** [comment]
Did you check ```S3.get_bkt(env, bkt)```

**Comment by s2maki** [comment]
To expand on @mdpradeep's answer, try something more like this:

For an S3 path such as "s3://mybucket/dir1/dir2", assume that `bkt="mybucket"; path="/dir1/dir2"`.
```
folder_prefix = path=="" ? path : rstrip(path, '/')*"/"
bucket_options = AWS.S3.GetBucketOptions(delimiter="/", prefix=folder_prefix)
AWS.S3.get_bkt(env, bkt; options=bucket_options)
```

Using the `delimiter` parameter in GetBucketOptions enables folder-like behavior in S3's API.  In that mode, you need to insure that the folder name you are listing ends with the path separator `/`.  Without the terminating slash, you'll get other files in the same folder that start with the folder's own name.  Without the delimiter setting, you will get a listing of every single file under that folder and not just one level deeper.

**Comment by samoconnor** [comment]
[`s3_list_objects` in AWSS3.jl](https://github.com/samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L246) has a `path =` option for this.

```julia
s3_list_objects(aws, "mybucket"; path="/dir1/dir2")
```

**Comment by jingpengwu** [comment]
Thanks a lot :) this works pretty well!

**Comment by s2maki** [comment]
Yes, AWS.jl is a fairly low-level, direct API implementation of a few of Amazon's services.  @samoconnor's packages are higher level, easier to use, and cover a broader scope of AWS services.  But they don't give you as much low-level control that is sometimes needed.

**Comment by samoconnor** [comment]
> But they don't give you as much low-level control that is sometimes needed.

@s2maki My intention is certainly not to preclude low-level control in any way.

If you have an example of some code where low-level access is needed I would be happy to look at how that could be done using `AWSCore.jl` and add it to the documentation as an example.

It is true that the packages based on `AWSCore.jl` try to present a high-level interface. However each package also has a low-level interface. Perhaps this is not obvious from the limited documentation. For example, AWSIAM.jl provides high level functions like `iam_whoami` and  `iam_create_user`, but has no function for creating InstanceProfiles. However, there is a low-level `AWSIAM.iam` function that provides access any IAM API.
For example, [AWSEC2.jl uses this as follows](https://github.com/samoconnor/AWSEC2.jl/blob/master/src/AWSEC2.jl#L115)...
```julia
        @protected try 

            iam(aws, Action = "CreateInstanceProfile",
                     InstanceProfileName = name,
                     Path = "/")
        catch e
            @ignore if e.code == "EntityAlreadyExists" end
        end


        @repeat 2 try 

            iam(aws, Action = "AddRoleToInstanceProfile",
                     InstanceProfileName = name,
                     RoleName = name)

        catch e
            @retry if e.code == "LimitExceeded"
                iam(aws, Action = "RemoveRoleFromInstanceProfile",
                         InstanceProfileName = name,
                         RoleName = name)
            end
        end
```

**Comment by s2maki** [comment]
It is true I don't have as much experience as I should with your packages.  I remember a few times looking at doing something particularly low level and not seeing a mechanism for it, but I don't remember what those are.  I certainly don't remember seeing the "Action" option that appears from your example here to expose every API call, so that may just have been my own problem with not looking hard enough.

The next time I have something I'm looking to do, I'll be sure to dig a little deeper and/or post my example.

**Comment by samoconnor** [comment]
@s2maki I guess it's mostly a flaw of my limited documentation. The `Action` option is a bit hidden...

The parameters like `Action`, `InstanceProfileName` and `RoleName` are documented in the [AWS API Reference](http://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateInstanceProfile.html#API_CreateInstanceProfile_Examples).

The `iam` function just takes these as `args...` and passes them to AWS as query string arguments.
```julia
function iam(aws; args...)

    aws = merge(aws, region = "us-east-1")

    query = StringDict(args)
    query["ContentType"] = "JSON"

    @repeat 4 try

        return do_request(post_request(aws, "iam", "2010-05-08", query))

    catch e
        @retry if e.code == "NoSuchEntity" end
    end
end
```

For example the `iam_whoami` function sets `Action` to `"GetUser"`:
```julia
iam_whoami(aws) = iam(aws, Action = "GetUser")["User"]["Arn"]
```

**Comment by jingpengwu** [comment]
I created a function to do it:
```
function s3_list_objects(env::AWSEnv, bkt::AbstractString, path::AbstractString)
    path = lstrip(path, '/')
    prefix = path=="" ? path : rstrip(path, '/')*"/"
    bucket_options = AWS.S3.GetBucketOptions(delimiter="/", prefix=prefix)
    resp = AWS.S3.get_bkt(env, bkt; options=bucket_options)

    ret = Vector{ASCIIString}()
    for content in resp.obj.contents
        fname = replace(content.key, prefix, "")
        if fname!=""
            push!(ret, fname)
        end
    end
    return ret
end

```
